[2024-03-10T16:34:02.690+0000] {logging_mixin.py:154} INFO - Changing /opt/***/logs/dag_id=dag_carbon_intensity/run_id=manual__2024-03-10T16:31:45.254367+00:00/task_id=load_data permission to 509
[2024-03-10T16:34:02.961+0000] {logging_mixin.py:154} INFO - Changing /opt/***/logs/dag_id=dag_carbon_intensity/run_id=manual__2024-03-10T16:31:45.254367+00:00/task_id=load_data permission to 509
[2024-03-10T16:34:03.038+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_carbon_intensity.load_data manual__2024-03-10T16:31:45.254367+00:00 [queued]>
[2024-03-10T16:34:03.055+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_carbon_intensity.load_data manual__2024-03-10T16:31:45.254367+00:00 [queued]>
[2024-03-10T16:34:03.057+0000] {taskinstance.py:1361} INFO - Starting attempt 3 of 4
[2024-03-10T16:34:03.076+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): load_data> on 2024-03-10 16:31:45.254367+00:00
[2024-03-10T16:34:03.085+0000] {standard_task_runner.py:57} INFO - Started process 7788 to run task
[2024-03-10T16:34:03.090+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'dag_carbon_intensity', 'load_data', 'manual__2024-03-10T16:31:45.254367+00:00', '--job-id', '147', '--raw', '--subdir', 'DAGS_FOLDER/dag_carbon_intensity.py', '--cfg-path', '/tmp/tmpgswc4o_4']
[2024-03-10T16:34:03.095+0000] {standard_task_runner.py:85} INFO - Job 147: Subtask load_data
[2024-03-10T16:34:03.372+0000] {logging_mixin.py:154} INFO - Changing /opt/***/logs/dag_id=dag_carbon_intensity/run_id=manual__2024-03-10T16:31:45.254367+00:00/task_id=load_data permission to 509
[2024-03-10T16:34:03.384+0000] {task_command.py:416} INFO - Running <TaskInstance: dag_carbon_intensity.load_data manual__2024-03-10T16:31:45.254367+00:00 [running]> on host b90b2ddba1ac
[2024-03-10T16:34:03.622+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_carbon_intensity' AIRFLOW_CTX_TASK_ID='load_data' AIRFLOW_CTX_EXECUTION_DATE='2024-03-10T16:31:45.254367+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-03-10T16:31:45.254367+00:00'
[2024-03-10T16:34:03.625+0000] {utils.py:63} ERROR - Error al obtener datos de https://api.carbonintensity.org.uk/intensity: 'str' object has no attribute 'strftime'
Traceback (most recent call last):
  File "/opt/airflow/scripts/utils.py", line 27, in get_data
    start_date_str = start.strftime('%Y-%m-%dT00:00Z')
AttributeError: 'str' object has no attribute 'strftime'
[2024-03-10T16:34:03.630+0000] {main_1.py:30} ERROR - Error al obtener datos de https://api.carbonintensity.org.uk/intensity: local variable 'df' referenced before assignment
[2024-03-10T16:34:03.631+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/scripts/main_1.py", line 31, in load_carbon_intensity_data
    raise e
  File "/opt/airflow/scripts/main_1.py", line 21, in load_carbon_intensity_data
    df_carbon_intensity = get_data(base_url,
  File "/opt/airflow/scripts/utils.py", line 65, in get_data
    return df
UnboundLocalError: local variable 'df' referenced before assignment
[2024-03-10T16:34:03.651+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_carbon_intensity, task_id=load_data, execution_date=20240310T163145, start_date=20240310T163403, end_date=20240310T163403
[2024-03-10T16:34:03.670+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 147 for task load_data (local variable 'df' referenced before assignment; 7788)
[2024-03-10T16:34:03.723+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-03-10T16:34:03.772+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
