[2024-03-10T16:42:35.301+0000] {logging_mixin.py:154} INFO - Changing /opt/***/logs/dag_id=dag_carbon_intensity/run_id=manual__2024-03-10T16:41:47.859175+00:00/task_id=load_data permission to 509
[2024-03-10T16:42:35.371+0000] {logging_mixin.py:154} INFO - Changing /opt/***/logs/dag_id=dag_carbon_intensity/run_id=manual__2024-03-10T16:41:47.859175+00:00/task_id=load_data permission to 509
[2024-03-10T16:42:35.982+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_carbon_intensity.load_data manual__2024-03-10T16:41:47.859175+00:00 [queued]>
[2024-03-10T16:42:35.999+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_carbon_intensity.load_data manual__2024-03-10T16:41:47.859175+00:00 [queued]>
[2024-03-10T16:42:36.000+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 4
[2024-03-10T16:42:36.018+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): load_data> on 2024-03-10 16:41:47.859175+00:00
[2024-03-10T16:42:36.026+0000] {standard_task_runner.py:57} INFO - Started process 8776 to run task
[2024-03-10T16:42:36.032+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'dag_carbon_intensity', 'load_data', 'manual__2024-03-10T16:41:47.859175+00:00', '--job-id', '157', '--raw', '--subdir', 'DAGS_FOLDER/dag_carbon_intensity.py', '--cfg-path', '/tmp/tmp8ejz4iqz']
[2024-03-10T16:42:36.037+0000] {standard_task_runner.py:85} INFO - Job 157: Subtask load_data
[2024-03-10T16:42:36.200+0000] {logging_mixin.py:154} INFO - Changing /opt/***/logs/dag_id=dag_carbon_intensity/run_id=manual__2024-03-10T16:41:47.859175+00:00/task_id=load_data permission to 509
[2024-03-10T16:42:36.220+0000] {task_command.py:416} INFO - Running <TaskInstance: dag_carbon_intensity.load_data manual__2024-03-10T16:41:47.859175+00:00 [running]> on host b90b2ddba1ac
[2024-03-10T16:42:36.356+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_carbon_intensity' AIRFLOW_CTX_TASK_ID='load_data' AIRFLOW_CTX_EXECUTION_DATE='2024-03-10T16:41:47.859175+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-03-10T16:41:47.859175+00:00'
[2024-03-10T16:42:36.359+0000] {logging_mixin.py:154} INFO - 2024-03-09T00:00:00+00:00
[2024-03-10T16:42:36.361+0000] {logging_mixin.py:154} INFO - 2024-03-10T00:00:00+00:00
[2024-03-10T16:42:36.362+0000] {utils.py:67} ERROR - Error al obtener datos de https://api.carbonintensity.org.uk/intensity: 'str' object has no attribute 'strftime'
Traceback (most recent call last):
  File "/opt/airflow/scripts/utils.py", line 29, in get_data
    start_date_str = start.strftime('%Y-%m-%dT00:00Z')
AttributeError: 'str' object has no attribute 'strftime'
[2024-03-10T16:42:36.367+0000] {main_1.py:30} ERROR - Error al obtener datos de https://api.carbonintensity.org.uk/intensity: local variable 'df' referenced before assignment
[2024-03-10T16:42:36.368+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/scripts/main_1.py", line 31, in load_carbon_intensity_data
    raise e
  File "/opt/airflow/scripts/main_1.py", line 21, in load_carbon_intensity_data
    df_carbon_intensity = get_data(base_url,
  File "/opt/airflow/scripts/utils.py", line 69, in get_data
    return df
UnboundLocalError: local variable 'df' referenced before assignment
[2024-03-10T16:42:36.389+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_carbon_intensity, task_id=load_data, execution_date=20240310T164147, start_date=20240310T164235, end_date=20240310T164236
[2024-03-10T16:42:36.405+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 157 for task load_data (local variable 'df' referenced before assignment; 8776)
[2024-03-10T16:42:36.417+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-03-10T16:42:36.471+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
